name: Run SQLCMD Script

#on:
#  push:
#    branches:
#      - main
#  workflow_dispatch:  # Allows manual triggering


jobs:
  execute-sqlcmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SQLCMD
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Run SQL script
        env:
          SYNAPSE_SERVER: ${{ secrets.SYNAPSE_SERVER }}
          SYNAPSE_USERNAME: ${{ secrets.SYNAPSE_USERNAME }}
          SYNAPSE_PASSWORD: ${{ secrets.SYNAPSE_PASSWORD }}
        run: |
          sqlcmd -S $SYNAPSE_SERVER -U $SYNAPSE_USERNAME -P $SYNAPSE_PASSWORD -i ./sql/queries.sql
