name: Run SQLCMD Script

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  execute-sqlcmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login via Service Principal
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: "SERVICE_PRINCIPAL"

      - name: Get Credentials from Key Vault
        id: get-credentials
        run: |
          set -e
          echo "Fetching username from Key Vault..."
          username=$(az keyvault secret show --name SYNAPSE-USERNAME --vault-name <Your-Key-Vault-Name> --query value -o tsv)
          if [ -z "$username" ]; then
            echo "Error: Unable to fetch SYNAPSE-USERNAME from Key Vault"
            exit 1
          fi
          echo "Fetching password from Key Vault..."
          password=$(az keyvault secret show --name SYNAPSE-PASSWORD --vault-name <Your-Key-Vault-Name> --query value -o tsv)
          if [ -z "$password" ]; then
            echo "Error: Unable to fetch SYNAPSE-PASSWORD from Key Vault"
            exit 1
          fi
          echo "SYNAPSE_USERNAME=$username" >> $GITHUB_ENV
          echo "SYNAPSE_PASSWORD=$password" >> $GITHUB_ENV

      - name: Set up SQLCMD
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Run SQL script
        env:
          SYNAPSE_SERVER: ${{ secrets.SYNAPSE_SERVER }}
          SYNAPSE_USERNAME: ${{ env.SYNAPSE_USERNAME }}
          SYNAPSE_PASSWORD: ${{ env.SYNAPSE_PASSWORD }}
        run: |
          sqlcmd -S $SYNAPSE_SERVER -U $SYNAPSE_USERNAME -P $SYNAPSE_PASSWORD -i ./sql/setup.sql
