name: Run SQLCMD Script

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

permissions:
  id-token: write  # Ensure write permissions for id-token
  contents: read   # Example: read permissions for repository contents
  
jobs:
  execute-sqlcmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
#          client-id: ${{ secrets.AZURE_CLIENT_ID }}
#          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
#          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#          auth-type: 'SERVICE_PRINCIPAL'  # Ensure auth-type is set to 'spn'
           creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Get Credentials from Key Vault
        id: get-credentials
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          scriptType: bash
          inlineScript: |
            username=$(az keyvault secret show --name SYNAPSE-USERNAME --vault-name adlssybapsekeyvault --query value -o tsv)
            password=$(az keyvault secret show --name SYNAPSE-PASSWORD --vault-name adlssybapsekeyvault --query value -o tsv)
            echo "SYNAPSE_USERNAME1=$username" >> $GITHUB_ENV
            echo "SYNAPSE_PASSWORD1=$password" >> $GITHUB_ENV

          
      - name: Set up SQLCMD
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Run SQL script
        env:
          SYNAPSE_SERVER: ${{ secrets.SYNAPSE_SERVER }}
          SYNAPSE_USERNAME: ${{ env.SYNAPSE_USERNAME }}
          SYNAPSE_PASSWORD: ${{ env.SYNAPSE_PASSWORD }}
        run: |
          sqlcmd -S $SYNAPSE_SERVER -U $SYNAPSE_USERNAME -P $SYNAPSE_PASSWORD -i ./sql/queries.sql
